DROP TABLE IF EXISTS T_E_MANIPULATION_CUSTOMER;

CREATE TABLE T_E_MANIPULATION_CUSTOMER
(
  ID         INT          NOT NULL PRIMARY KEY AUTO_INCREMENT
  ,
  LAST_NAME  VARCHAR(100) NOT NULL
  ,
  FIRST_NAME VARCHAR(100) NOT NULL
  ,
  EMAIL      VARCHAR(100) NOT NULL
  ,
  ADDRESS_FK INT
);


DROP TABLE IF EXISTS T_E_MANIPULATION_ADDRESS;

CREATE TABLE T_E_MANIPULATION_ADDRESS
(
  ID       INT          NOT NULL PRIMARY KEY AUTO_INCREMENT
  ,
  STREET   VARCHAR(100) NOT NULL
  ,
  ZIP_CODE VARCHAR(100) NOT NULL
  ,
  COUNTRY  VARCHAR(100) NOT NULL
  ,
  CITY     VARCHAR(100) NOT NULL
);

-- ALTER TABLE T_E_MANIPULATION_ADDRESS
--   ADD FOREIGN KEY (ID) REFERENCES T_E_MANIPULATION_CUSTOMER (ADDRESS_FK);

SELECT  * FROM T_E_MANIPULATION_CUSTOMER;
SELECT  * FROM T_E_MANIPULATION_ADDRESS;