DROP TABLE IF EXISTS T_E_INHERITANCE_JOINED_ITEM;

CREATE TABLE T_E_INHERITANCE_JOINED_ITEM
(
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY
  ,DTYPE VARCHAR(256)
  ,NAME VARCHAR(256)
);

SELECT * FROM T_E_INHERITANCE_JOINED_ITEM;

DROP TABLE IF EXISTS T_E_INHERITANCE_JOINED_CD;

CREATE TABLE T_E_INHERITANCE_JOINED_CD
(
   ID INT NOT NULL PRIMARY KEY
  ,NUMBER VARCHAR(256)
);

DROP TABLE IF EXISTS T_E_INHERITANCE_JOINED_BOOK;

CREATE TABLE T_E_INHERITANCE_JOINED_BOOK
(
   ID INT  NOT NULL PRIMARY KEY
  ,AUTHOR VARCHAR(256)
);

SELECT * FROM T_E_INHERITANCE_JOINED_ITEM;
SELECT * FROM T_E_INHERITANCE_JOINED_CD;
SELECT * FROM T_E_INHERITANCE_JOINED_BOOK;