DROP TABLE IF EXISTS T_E_INHERITANCE_TABLE_PER_CLASS_GENERATOR;
CREATE TABLE T_E_INHERITANCE_TABLE_PER_CLASS_GENERATOR
(
   ID   BIGINT NOT NULL AUTO_INCREMENT
  ,NAME VARCHAR(100)
);


DROP TABLE IF EXISTS T_E_INHERITANCE_TABLE_PER_CLASS_ITEM;

CREATE TABLE T_E_INHERITANCE_TABLE_PER_CLASS_ITEM
(
  ID     INT NOT NULL
  ,
  DTYPE  VARCHAR(256)
  ,
  NAME   VARCHAR(256)
);

SELECT *
FROM T_E_INHERITANCE_TABLE_PER_CLASS_ITEM;

DROP TABLE IF EXISTS T_E_INHERITANCE_TABLE_PER_CLASS_CD;

CREATE TABLE T_E_INHERITANCE_TABLE_PER_CLASS_CD
(
  ID     INT NOT NULL
  ,
  NAME   VARCHAR(256)
  ,
  NUMBER VARCHAR(256)
);

SELECT *
FROM T_E_INHERITANCE_TABLE_PER_CLASS_CD;

DROP TABLE IF EXISTS T_E_INHERITANCE_TABLE_PER_CLASS_BOOK;

CREATE TABLE T_E_INHERITANCE_TABLE_PER_CLASS_BOOK
(
  ID     INT NOT NULL
  ,
  NAME   VARCHAR(256)
  ,
  AUTHOR VARCHAR(256)
);

SELECT *
FROM T_E_INHERITANCE_TABLE_PER_CLASS_ITEM;
SELECT *
FROM T_E_INHERITANCE_TABLE_PER_CLASS_CD;
SELECT *
FROM T_E_INHERITANCE_TABLE_PER_CLASS_BOOK;