DROP TABLE IF EXISTS T_E_CUSTOMER;

CREATE TABLE T_E_CUSTOMER(
   id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
  ,firstName VARCHAR(100)
  ,ADDRESS_FK BIGINT
);

DROP TABLE IF EXISTS T_E_ADDRESS;
CREATE TABLE T_E_ADDRESS(
   id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
  ,street VARCHAR(100)
);

ALTER TABLE T_E_ADDRESS ADD FOREIGN KEY (ID) REFERENCES T_E_CUSTOMER(ADDRESS_FK);

select * from T_E_CUSTOMER;
select * from T_E_ADDRESS;



