DROP TABLE IF EXISTS T_E_NOTE ;
CREATE TABLE T_E_NOTE AS SELECT * FROM CSVREAD('C:\Users\rrnezh\programmer\git\java-ee-examples\cdi-book-service\src\resources\prepared-H2DB\T_E_NOTE.csv', null, 'charset=UTF-8');

select 
	ID
	,NAME
	,ISHIDE
from T_E_NOTE;

ALTER TABLE T_E_NOTE ALTER COLUMN ID  SET NOT NULL;
ALTER TABLE T_E_NOTE ALTER COLUMN ID  INT;
ALTER TABLE T_E_NOTE ALTER COLUMN ISHIDE  BOOLEAN;

CREATE PRIMARY KEY ON T_E_NOTE (ID);

--==========================================================================

DROP TABLE IF EXISTS  T_E_NOTE_DETAIL ;
CREATE TABLE T_E_NOTE_DETAIL AS SELECT * FROM CSVREAD('C:\Users\rrnezh\programmer\git\java-ee-examples\cdi-book-service\src\resources\prepared-H2DB\T_E_NOTE_DETAIL.csv', null, 'charset=UTF-8');

select 
	ID
	,TEXT
	,LINK
from T_E_NOTE_DETAIL;

ALTER TABLE T_E_NOTE_DETAIL ALTER COLUMN ID  SET NOT NULL;
ALTER TABLE T_E_NOTE_DETAIL ALTER COLUMN ID  INT;

CREATE PRIMARY KEY ON T_E_NOTE_DETAIL (ID);

ALTER TABLE T_E_NOTE_DETAIL ADD FOREIGN KEY(ID) REFERENCES T_E_NOTE (ID) ON DELETE CASCADE ON UPDATE CASCADE;

--==========================================================================

DROP TABLE IF EXISTS  T_E_NOTE_TIMESTAMP ;
CREATE TABLE T_E_NOTE_TIMESTAMP AS SELECT * FROM CSVREAD('C:\Users\rrnezh\programmer\git\java-ee-examples\cdi-book-service\src\resources\prepared-H2DB\T_E_NOTE_TIMESTAMP.csv', null, 'charset=UTF-8');

select
	ID
	,DATEADD
	,DATEEDIT
from T_E_NOTE_TIMESTAMP;

ALTER TABLE T_E_NOTE_TIMESTAMP ALTER COLUMN ID  SET NOT NULL;
ALTER TABLE T_E_NOTE_TIMESTAMP ALTER COLUMN ID  INT;

ALTER TABLE T_E_NOTE_TIMESTAMP ADD COLUMN DATEADD_TEMP  TIMESTAMP;
ALTER TABLE T_E_NOTE_TIMESTAMP ADD COLUMN DATEEDIT_TEMP  TIMESTAMP;

CREATE PRIMARY KEY ON T_E_NOTE_TIMESTAMP (ID);
ALTER TABLE T_E_NOTE_TIMESTAMP ADD FOREIGN KEY(ID) REFERENCES T_E_NOTE (ID) ON DELETE CASCADE ON UPDATE CASCADE;

SELECT
	ID
	,DATEADD
	,DATEEDIT
	,DATEADD_TEMP
	,DATEEDIT_TEMP
FROM T_E_NOTE_TIMESTAMP;

SELECT parsedatetime(DATEADD, 'dd-MM-yyyy hh:mm:ss') FROM T_E_NOTE_TIMESTAMP;
SELECT case when DATEEDIT = '' then null else parsedatetime(DATEEDIT, 'dd-MM-yyyy hh:mm:ss') end FROM T_E_NOTE_TIMESTAMP;

UPDATE T_E_NOTE_TIMESTAMP
	SET 
		DATEADD_TEMP =  parsedatetime(DATEADD, 'dd-MM-yyyy hh:mm:ss'),
		DATEEDIT_TEMP =  case when DATEEDIT = '' then null else parsedatetime(DATEEDIT, 'dd-MM-yyyy hh:mm:ss') end;

ALTER TABLE T_E_NOTE_TIMESTAMP DROP COLUMN DATEADD;
ALTER TABLE T_E_NOTE_TIMESTAMP DROP COLUMN DATEEDIT;

ALTER TABLE T_E_NOTE_TIMESTAMP ADD COLUMN DATEADD  TIMESTAMP;
ALTER TABLE T_E_NOTE_TIMESTAMP ADD COLUMN DATEEDIT  TIMESTAMP;

UPDATE T_E_NOTE_TIMESTAMP
	SET 
		DATEADD =  DATEADD_TEMP,
		DATEEDIT = DATEEDIT_TEMP;

ALTER TABLE T_E_NOTE_TIMESTAMP DROP COLUMN DATEADD_TEMP;
ALTER TABLE T_E_NOTE_TIMESTAMP DROP COLUMN DATEEDIT_TEMP;

SELECT
	ID
	,DATEADD
	,DATEEDIT
FROM T_E_NOTE_TIMESTAMP;